### ISSUE TITLE
step_ca_root_password is confusing

### ISSUE THREAD

**Issue by patsevanton** [maxhoesel-ansible/ansible-collection-smallstep#390]
Hello! Thanks for ansible-collection-smallstep! 
I read example:
```
      vars:
        step_ca_name: Foobar Internal CA
        step_ca_root_password: "incredibly secret password"
        step_ca_intermediate_password: "very secret password"
```
Where use step_ca_root_password ? 
what is the step_ca_root_password for?
