### ISSUE TITLE
[Bug ]mv: cannot stat '/tmp/step-ca_0.28.1/step-ca

### ISSUE THREAD

**Issue by Dialgatrainer02** [maxhoesel-ansible/ansible-collection-smallstep#459]
hello, this is my first time using the collection and its failing with this error

```yml
---
- name: Install step ca
  hosts: stepCA
  become: true
  pre_tasks:
    - name: Install compression libary
      ansible.builtin.package:
        name: tar
        state: present
      become: true
  tasks:
    # Install and initialize the CA server.
    # There are a lot of configuration options, see the step_ca README for details
    - name: Install step-ca
      ansible.builtin.include_role:
        name: maxhoesel.smallstep.step_ca
      vars:
        step_ca_name: Foobar Internal CA
        step_ca_root_password: "incredibly secret password"
        step_ca_intermediate_password: "very secret password"
        step_ca_ssh: true

    # The CA root cert fingerprint is used by clients to verify the authenticity of your CA.
    # You can save the output of this task and then pass it on to any client that you want to trust the CA.
    - name: Get root CA fingerprint # noqa no-changed-when
      ansible.builtin.command: 'step-cli certificate fingerprint /etc/step-ca/certs/root_ca.crt'
      register: root_ca_fp
    - name: Show root CA fingerprint
      ansible.builtin.debug:
        msg: "Fingerprint of root cert: {{ root_ca_fp.stdout }}"

```

this is running on an almalinux lxc and gives the error

```
fatal: [stepCA]: FAILED! => {"changed": true, "cmd": "set -o pipefail && mv -Z /tmp/step-ca_0.28.1/step-ca /usr/bin\n", "delta": "0:00:00.004779", "end": "2024-12-21 23:08:55.688132", "msg": "non-zero return code", "rc": 1, "start": "2024-12-21 23:08:55.683353", "stderr": "mv: cannot stat '/tmp/step-ca_0.28.1/step-ca': No such file or directory", "stderr_lines": ["mv: cannot stat '/tmp/step-ca_0.28.1/step-ca': No such file or directory"], "stdout": "", "stdout_lines": []}
```
apparently this was fixed in a pr but im still having the issue 

host is on almalinux 9 and controller is on archlinux

**Comment by BrianInAz** [comment]
I'm getting the same error. It looks like step-ca is actually sitting in /tmp rather than the folder it's looking at.

**Comment by oliversalzburg** [comment]
There hasn't been a release in a while. You can reference the collection from git:

```yml
  - name: https://github.com/maxhoesel-ansible/ansible-collection-smallstep
    type: git
    version: 187c10bb7c42a5b573d90df09bd8c27994ee5b96
```
